[versions]
fabric-loader = "0.19.3"
fabric-loom = "1.17-SNAPSHOT"
minecraft = "1.8.9"
kotlin = "2.4.0"
lwjgl = "3.4.1"
joml = "1.10.8"
yarn = "1.8.9+build.4"
legacy-lwjgl3 = "1.4.0-beta.11"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
lwjgl-bom = { module = "org.lwjgl:lwjgl-bom", version.ref = "lwjgl" }
lwjgl = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
lwjgl-opengl = { module = "org.lwjgl:lwjgl-opengl", version.ref = "lwjgl" }
lwjgl-openal = { module = "org.lwjgl:lwjgl-openal", version.ref = "lwjgl" }
lwjgl-sdl = { module = "org.lwjgl:lwjgl-sdl", version.ref = "lwjgl" }
lwjgl-vulkan = { module = "org.lwjgl:lwjgl-vulkan", version.ref = "lwjgl" }
lwjgl-vma = { module = "org.lwjgl:lwjgl-vma", version.ref = "lwjgl" }
lwjgl-shaderc = { module = "org.lwjgl:lwjgl-shaderc", version.ref = "lwjgl" }
joml = { module = "org.joml:joml", version.ref = "joml" }
legacy-yarn = { module = "net.legacyfabric:legacy-yarn", version.ref = "yarn" }
legacy-lwjgl3 = { module = "io.github.moehreag:legacy-lwjgl3", version.ref = "legacy-lwjgl3" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }
ploceus = { id = "ploceus", version.ref = "fabric-loom" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }